### ISSUE TITLE
Request: Server Logs

### ISSUE THREAD

**Issue by WilliamDraco** [ravenmyst/NWNLogRotator#1]
Project looks great, especially love the rich html parsing of the logs.

Is it on the cards to extend the capabilities to also be able to capture the running of nwserver, and rotating server-logs in a similar fashion (Although separately, as the host running the server might also use the client, and I think they should rotate independently).

Unsure of how the parsing works, it'd be a great half-step to just dump the serverlogs in unformatted html for a while until the parser was built-up to manage it.

Thanks very much for considering.

**Comment by ravenmyst** [comment]
Yep, it's totally possible, at least some degree, off a surface glance. I don't have many example server logs to go with, to test my Regular Expressions against, but when I'm done the current list of improvements, I'll look into getting various log sources and types and see what patterns can be beautified.

**Comment by WilliamDraco** [comment]
In my particular use-case, the server is only online for a few hours a week - So parsing when it goes down is excellent (Especially if it crashes. Over the week we can remember to manually copy-paste to rotate, but if it crashes it's easy to forget in the rush to bring the server back up.)

Agree that for broader use-cases there should probably be some sort of "every x-hours" rotation, but I don't know enough about programming to comment on that feasibility 😅

**Comment by ravenmyst** [comment]
If you have any non-private (or censored) logs you could provide it would help. Currently I don't have any server logs (as I'm not as active atm in the game) and I'd like to have at least a few before proceeding.

**Comment by ravenmyst** [comment]
Do you have any example server logs, with obfuscated private text I could use as a reference? I don't have much time these days to play and I'd like to build a collection before parsing.

**Comment by WilliamDraco** [comment]
I'll get one prepared with as much of the different types of content as I can.

**Comment by WilliamDraco** [comment]
[nwserverLog1.txt](https://github.com/ravenmyst/NWNLogRotator/files/3776600/nwserverLog1.txt)
Sorry for the delay. Please find attached an example server log extract. I've cut out a lot of repeated stuff everywhere, so No. of players might not match up etc. The only interaction I can think of that is not covered by this is a Server Message sent via the server console. I'll whip up a quick example of that and see if it appears & differs from anything here.

Note that anything following a # is a comment by myself. The actual server log does not contain any #'s

**Comment by ravenmyst** [comment]
Thanks for getting that to me! I'll try to work on implementing this somehow soon. let me know if you find anything more about the Server Message.

**Comment by findell666** [comment]
Hello, I stumbled into the same interrogation. Have you managed to write something for the nwserver logs rotation ? Thank you :)

**Comment by ravenmyst** [comment]
I will re-look into this now hopefully after the next round of client changes in the other open issue. I'm happy to see it still being used and I would love to deliver a better product that also encompasses the server log as well.

**Comment by ravenmyst** [comment]
So it occurs to me that I don't really have a 'huge' server log, so to speak, though the example is helpful, I don't know exactly what the possibilities of text are, what differs between servers, and without that I can't really make a helpful tool.

**Comment by ravenmyst** [comment]
Well, I did the preliminary part, of including it. I don't have many server logs to parse, so it doesn't do anything advanced. If you could please provide feedback in a new issue that would be fantastic.

Good luck!
