### ISSUE TITLE
Humble suggestions

### ISSUE THREAD

**Issue by n0cturn41** [ravenmyst/NWNLogRotator#2]
Hi ravenmyst,

Thanks for this tool once again, it's been really helpful. I understand continual support isn't a priority since you no longer play, but I'll put through some of my own feature suggestions in any case:

1.-- Extra option for the tool to interpret different emote symbols, e.g. [], as well as **.
2.-- Noticed that in some cases the tool takes a bit longer to read the log and create the file after a long session. Shutting down shortly after quitting NWN of course will prevent the process completing and the log being written. A notification/reminder pop up of current parsing might be helpful.
3.-- Option to add certain lines to the tool ourselves that would be excluded in the written log.

Things that aren't in the log and not so easily to pick up on:
1.-- Log to automatically pick up on character name and include into the filename for sorting purposes.
2.-- Log to automatically pick up the server name and include into the filename for sorting purposes.

Cheers!

**Comment by ravenmyst** [comment]
These are good ideas. I think each of them is definitely possible, and would be good to have. I hope to have the time and energy to implement them soon.

I'm glad you enjoy the program!

**Comment by ravenmyst** [comment]
Just completed 3 items on your list. Hopefully they are helpful!
